### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by NullParameter**
A fair amount of code cleanup.  Adding some correctness around file
usage, and removing a fair amount of unnecessary code.

### CODE REVIEW

**Comment by binarySwordsman** [comment]
So, just one issue:  the thing you're doing with basics doesn't work because they appear as cards in some sets, so they'd be on the list multiple times. If you could fix that and redo the pr, that would be great. Thanks!

**Comment by NullParameter** [comment]
It's a Set now, not a List, so there will never be any duplicates.

**Comment by binarySwordsman** [comment]
No, I think you add basics to the list, not the set.

**Comment by NoahGleason** [comment]
NVM, I'm dumb and can't read. Also, what do you think about using a for loop to read through files with BufferedReader?

**Comment by NullParameter** [comment]
The while loop is straight to the point and gets the job done.  Is there a benefit you're hoping to gain by moving to a for loop?

**Comment by binarySwordsman** [comment]
It's the same number of lines (for (String line  = br.readLine() ; line != null; line = br.readLine())), and a bit easier to read and understand.

**Comment by NullParameter** [comment]
Code should be all about readability.  If you find it easier to read that way, then make it so.

**Pull request merged**
